// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADkW8OUUn-pNgviy3L687K3RRg3ztJIZk',
    appId: '1:3779598428:web:7bd8c7b1bb5e7a6131ee99',
    messagingSenderId: '3779598428',
    projectId: 'fruits-hub-ahmed',
    authDomain: 'fruits-hub-ahmed.firebaseapp.com',
    storageBucket: 'fruits-hub-ahmed.firebasestorage.app',
    measurementId: 'G-8Z965PX7QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_okXotcizTx6zOc6ioRTmjmKW4oLA_vQ',
    appId: '1:3779598428:android:2586576d8950f78831ee99',
    messagingSenderId: '3779598428',
    projectId: 'fruits-hub-ahmed',
    storageBucket: 'fruits-hub-ahmed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Hmd2c7rUtyqCkgsNCSmKKTg-o1h-lms',
    appId: '1:3779598428:ios:6cd91e1375baa09a31ee99',
    messagingSenderId: '3779598428',
    projectId: 'fruits-hub-ahmed',
    storageBucket: 'fruits-hub-ahmed.firebasestorage.app',
    androidClientId: '3779598428-g2k8v2jeoila6gs27of9tg3r5va86nu8.apps.googleusercontent.com',
    iosClientId: '3779598428-eubnlo8o0o1c6k34f47nlljsup13o9de.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Hmd2c7rUtyqCkgsNCSmKKTg-o1h-lms',
    appId: '1:3779598428:ios:6cd91e1375baa09a31ee99',
    messagingSenderId: '3779598428',
    projectId: 'fruits-hub-ahmed',
    storageBucket: 'fruits-hub-ahmed.firebasestorage.app',
    androidClientId: '3779598428-g2k8v2jeoila6gs27of9tg3r5va86nu8.apps.googleusercontent.com',
    iosClientId: '3779598428-eubnlo8o0o1c6k34f47nlljsup13o9de.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADkW8OUUn-pNgviy3L687K3RRg3ztJIZk',
    appId: '1:3779598428:web:72e409be452b990c31ee99',
    messagingSenderId: '3779598428',
    projectId: 'fruits-hub-ahmed',
    authDomain: 'fruits-hub-ahmed.firebaseapp.com',
    storageBucket: 'fruits-hub-ahmed.firebasestorage.app',
    measurementId: 'G-MDGJSL8XN3',
  );
}
